apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: hellodocker
        image: hellodocker:latest
        ports:
        - containerPort: 8000
